CREATE DATABASE SchoolMapping;

USE SchoolMapping;

CREATE TABLE TB_Usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
		CONSTRAINT chkArroba CHECK(email LIKE '%@%'),
    senha VARCHAR(30) NOT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);